### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by fiblan** [fangfufu/Linux-Fake-Background-Webcam#11]
```
fakecam_1  | Please CTRL-C to reload the background and foreground images
fakecam_1  | Traceback (most recent call last):
fakecam_1  |   File "fake.py", line 108, in <module>
fakecam_1  |     frame = get_frame(cap, background)
fakecam_1  |   File "fake.py", line 93, in get_frame
fakecam_1  |     frame[:,:,c] = frame[:,:,c] * mask + background[:,:,c] * (1 - mask)
fakecam_1  | ValueError: operands could not be broadcast together with shapes (720,1280) (480,640)
```
I get this error with and without docker.

**Comment by fangfufu** [comment]
Change https://github.com/fangfufu/Linux-Fake-Background-Webcam/blob/master/fakecam/fake.py#L11 to ``(480, 640)``, your webcam does not support ``(720,1280)``.

**Comment by fangfufu** [comment]
Your webcam does not support 1280x720. I changed the code so now it detects the actual resolution of the webcam stream.
