### ISSUE TITLE
Background image interpreted as video

### ISSUE THREAD

**Issue by amamut** [fangfufu/Linux-Fake-Background-Webcam#157]
I am able to open the image with `feh` no problem. But when I use it as a background image the process fails to start up:
```
Running...
Please CTRL-C to pause and reload the background / foreground images
Please CTRL-\ to exit
[ERROR:0] global /tmp/pip-req-build-agffqapq/opencv/modules/videoio/src/cap.cpp (160) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.3) /tmp/pip-req-build-agffqapq/opencv/modules/videoio/src/cap_images.cpp:293: error: (-215:Assertion failed) !_filename.empty() in function 'open'


Traceback (most recent call last):
  File "/home/amamut/projects/lib/Linux-Fake-Background-Webcam/./fake.py", line 517, in <module>
    main()
  File "/home/amamut/projects/lib/Linux-Fake-Background-Webcam/./fake.py", line 513, in main
    cam.run()
  File "/home/amamut/projects/lib/Linux-Fake-Background-Webcam/./fake.py", line 290, in run
    self.load_images()
  File "/home/amamut/projects/lib/Linux-Fake-Background-Webcam/./fake.py", line 177, in load_images
    raise RuntimeError("Couldn't open video '{}'".format(
RuntimeError: Couldn't open video '/home/amamut/projects/personal/dotfiles/wallpapers/MrsHappy-445-2-1024x736.jpg'
```

**Comment by fangfufu** [comment]
What did you type in the command line?

**Comment by amamut** [comment]
`./fake.py -c config-example.ini`

file contents
```
width = 1920
height = 1080
fps = 60
webcam-path = /dev/video0
v4l2loopback-path = /dev/video2
#image-folder = "~/project/personal/dotfiles/wallpapers"
background-image = "/home/amamut/projects/personal/dotfiles/wallpapers/MrsHappy-445-2-1024x736.jpg"
no-background = yes
background-blur = 21
background-blur-sigma-frac = 3
background-keep-aspect = no
no-foreground = yes
background-mask-update-speed = 10
```

**Comment by fangfufu** [comment]
Have you tried the default background image shipped with this repository? Does that work?

**Comment by amamut** [comment]
Yes the default image works.

**Comment by fangfufu** [comment]
Do you mind sending me your image then?

**Comment by fangfufu** [comment]
Have you tried setting ``background-image`` to the default image, does it work?

**Comment by amamut** [comment]
![yacht](https://user-images.githubusercontent.com/963908/132776360-0bb96410-3028-4103-85d1-1b8e763109e0.jpg)

Same thing with the `background.jpg` in the repo only when I use `./background.jpg`. Using `background.jpg` works fine:
```
[ERROR:0] global /tmp/pip-req-build-agffqapq/opencv/modules/videoio/src/cap.cpp (160) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.3) /tmp/pip-req-build-agffqapq/opencv/modules/videoio/src/cap_images.cpp:293: error: (-215:Assertion failed) !_filename.empty() in function 'open'


Traceback (most recent call last):
  File "/home/amamut/projects/lib/Linux-Fake-Background-Webcam/./fake.py", line 517, in <module>
    main()
  File "/home/amamut/projects/lib/Linux-Fake-Background-Webcam/./fake.py", line 513, in main
    cam.run()
  File "/home/amamut/projects/lib/Linux-Fake-Background-Webcam/./fake.py", line 290, in run
    self.load_images()
  File "/home/amamut/projects/lib/Linux-Fake-Background-Webcam/./fake.py", line 177, in load_images
    raise RuntimeError("Couldn't open video '{}'".format(
RuntimeError: Couldn't open video './background.jpg'
```

Copying my image to the directory where the code lives works.

**Comment by fangfufu** [comment]
It is now fixed.
