### ISSUE TITLE
Unable to launch program - "Invalid argument" error

### ISSUE THREAD

**Issue by d3-X-t3r** [fangfufu/Linux-Fake-Background-Webcam#170]
I'm unable to run this program, compiled directly from the latest git clone without any errors.
```
$ python3 fake.py

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Real camera original values are set as: 640x480 with 30 FPS and video codec 1448695129
Real camera new values are set as: 1280x720 with 30 FPS and video codec 1196444237
Traceback (most recent call last):
  File "/home/dexter/Downloads/Linux-Fake-Background-Webcam/fake.py", line 494, in <module>
    main()
  File "/home/dexter/Downloads/Linux-Fake-Background-Webcam/fake.py", line 483, in main
    cam = FakeCam(args)
  File "/home/dexter/Downloads/Linux-Fake-Background-Webcam/fake.py", line 120, in __init__
    self.fake_cam = pyfakewebcam.FakeWebcam(self.v4l2loopback_path, self.width,
  File "/home/dexter/.local/lib/python3.9/site-packages/pyfakewebcam/pyfakewebcam.py", line 54, in __init__
    fcntl.ioctl(self._video_device, _v4l2.VIDIOC_S_FMT, self._settings)
OSError: [Errno 22] Invalid argument
```
OS: Arch Linux x64
python3 version: 3.9.7
pip3 version: pip 21.3

```
$ v4l2-ctl -D 

Driver Info:
	Driver name      : uvcvideo
	Card type        : HP HD Camera: HP HD Camera
	Bus info         : usb-0000:00:14.0-9
	Driver version   : 5.14.14
	Capabilities     : 0x84a00001
		Video Capture
		Metadata Capture
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x04200001
		Video Capture
		Streaming
		Extended Pix Format
Media Driver Info:
	Driver name      : uvcvideo
	Model            : HP HD Camera: HP HD Camera
	Serial           : 01.00.00
	Bus info         : usb-0000:00:14.0-9
	Media version    : 5.14.14
	Hardware revision: 0x00000006 (6)
	Driver version   : 5.14.14
Interface Info:
	ID               : 0x03000002
	Type             : V4L Video
Entity Info:
	ID               : 0x00000001 (1)
	Name             : HP HD Camera: HP HD Camera
	Function         : V4L2 I/O
	Flags         : default
	Pad 0x01000007   : 0: Sink
	  Link 0x02000013: from remote pad 0x100000a of entity 'Extension 4': Data, Enabled, Immutable
```

**Comment by ashleysommer** [comment]
I had this same problem. I ran `v4l2-ctl -D --list-devices` and saw that my fake device was actually on `/dev/video6`
So I changed v4l2loopback-path in config.ini to `/dev/video6` (and changed my webcam-path to the correct device for my real webcam too) then the software works as expected.

**Comment by fangfufu** [comment]
I have the same problem too now. I upgraded my Debian, that's why. 

It might be related to this:
https://github.com/jacksonliam/mjpg-streamer/issues/229

**Comment by raffaem** [comment]
I have the exact same problem:
```
$ python3 fake.py
Real camera original values are set as: 0x0 with 0 FPS and video codec 0
Cannot set camera property 6 to 1196444237. Defaulting to auto-detected property set by opencv
Cannot set camera property 3 to 1280. Defaulting to auto-detected property set by opencv
Cannot set camera property 4 to 720. Defaulting to auto-detected property set by opencv
Cannot set camera property 5 to 30. Defaulting to auto-detected property set by opencv
Real camera new values are set as: 0x0 with 0 FPS and video codec 0
Traceback (most recent call last):
  File "/run/media/raffaele/55ab61c4-83cf-4d9f-a5cd-7fcfdc14b4fb/data/progetti_altrui/Linux-Fake-Background-Webcam/fake.py", line 495, in <module>
    main()
  File "/run/media/raffaele/55ab61c4-83cf-4d9f-a5cd-7fcfdc14b4fb/data/progetti_altrui/Linux-Fake-Background-Webcam/fake.py", line 484, in main
    cam = FakeCam(args)
  File "/run/media/raffaele/55ab61c4-83cf-4d9f-a5cd-7fcfdc14b4fb/data/progetti_altrui/Linux-Fake-Background-Webcam/fake.py", line 120, in __init__
    self.fake_cam = pyfakewebcam.FakeWebcam(self.v4l2loopback_path, self.width,
  File "/home/raffaele/pyvenv/virtualwebcam/lib64/python3.10/site-packages/pyfakewebcam/pyfakewebcam.py", line 54, in __init__
    fcntl.ioctl(self._video_device, _v4l2.VIDIOC_S_FMT, self._settings)
OSError: [Errno 22] Invalid argument
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
```

I have tried everything.

Here are my devices:
```
$ v4l2-ctl -D --list-devices
OBS Virtual Camera (platform:v4l2loopback-000):
	/dev/video0

HD WebCam: HD WebCam (usb-0000:00:14.0-5):
	/dev/video1
	/dev/video2
	/dev/media0

Driver Info:
	Driver name      : v4l2 loopback
	Card type        : OBS Virtual Camera
	Bus info         : platform:v4l2loopback-000
	Driver version   : 5.16.9
	Capabilities     : 0x85208002
		Video Output
		Video Memory-to-Memory
		Read/Write
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x05208002
		Video Output
		Video Memory-to-Memory
		Read/Write
		Streaming
		Extended Pix Format
```

**Comment by raffaem** [comment]
[allo-'s virtual_webcam_background](github.com/allo-/virtual_webcam_background) works with v4l2loopback.

So I thinks it's a problem of this software.

**Comment by raffaem** [comment]
The default values where all wonrg for me.

It could not work not now not ever.

It worked after I called it like that:

```
python3 fake.py --webcam-path /dev/video1 --v4l2loopback-path /dev/video0
```

**Comment by dragonxtek** [comment]
I have the same issue. Webcamoid works but no fake.py

**Comment by fangfufu** [comment]
This looks like end user configuration issue.
