### ISSUE TITLE
line 71, in get_frame_rate ... ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by alkinnon** [fangfufu/Linux-Fake-Background-Webcam#183]
Hi,
First off, this project looks great, thank you for sharing. I hope this is an easy issue to resolve and just down to my ignorance.

Using Linux Mint 21 on an old HP 8200 slim PC, with a logitech ps2 eyetoy as the webcam. 
The Webcam works and accessible on video2. I have v4l2 devices 0 and 1 (haven't worked out how to remove the one I don't need yet).
 
I get the error in the title when I try to start things up (full error listed below).

`Command python3 fake.py --config config.ini`

Traceback (most recent call last):
  File "/home/le19am/Linux-Fake-Background-Webcam/fake.py", line 495, in <module>
    main()
  File "/home/le19am/Linux-Fake-Background-Webcam/fake.py", line 484, in main
    cam = FakeCam(args)
  File "/home/le19am/Linux-Fake-Background-Webcam/fake.py", line 112, in __init__
    self.real_cam = RealCam(self.webcam_path,
  File "/home/le19am/Linux-Fake-Background-Webcam/fake.py", line 21, in __init__
    self.get_camera_values("original")
  File "/home/le19am/Linux-Fake-Background-Webcam/fake.py", line 34, in get_camera_values
    self.get_frame_rate(),
  File "/home/le19am/Linux-Fake-Background-Webcam/fake.py", line 71, in get_frame_rate
    return int(self.cam.get(cv2.CAP_PROP_FPS))
ValueError: cannot convert float NaN to integer
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

config.ini content:
```
width = 320
height = 240
fps = 30
; no-background = yes
background-keep-aspect = no
no-foreground = yes
webcam-path = /dev/video2
threshold = 50

width = 320
height = 240
fps = 30
; no-background = yes
background-keep-aspect = no
no-foreground = yes
webcam-path = /dev/video2
v4l2loopback-path = /dev/video0
threshold = 50
```

Thanks for your time,
Al

**Comment by alkinnon** [comment]
I think this is a result of issues with v4l2loopback setup. 
My camera input works, but the virtual cam output doesn't. Tried using  webcamoid to test creating a virtual camera with some filters, and it freezes as soon as I create one. Perhaps further info could be output to identify the source of the issue, or check the video devices work?

**Comment by alkinnon** [comment]
After a lot of messing about, I've managed to get past this. Experiencing different problems now unrelated to this issue.
