### ISSUE TITLE
Mask request failed

### ISSUE THREAD

**Issue by danyill** [fangfufu/Linux-Fake-Background-Webcam#3]
Thanks for this, I was keen to try it out.

I get the following from the `fakecam` image:

```
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
mask request failed, retrying
Traceback (most recent call last):
  File "fake.py", line 69, in <module>
    frame = get_frame(cap, background_scaled)
  File "fake.py", line 50, in get_frame
    frame[:,:,c] = frame[:,:,c]*mask + background_scaled[:,:,c]*inv_mask
ValueError: operands could not be broadcast together with shapes (720,1280) (480,640) 
```

Looks like a mismatch between resolutions or similar?

**Comment by fangfufu** [comment]
Please remove the containers and images, and try the cpu-only branch that I have just pushed in. By the look of it, the bodypix container isn't working.
