### ISSUE TITLE
Can't pick correct size?

### ISSUE THREAD

**Issue by rpavlik** [fangfufu/Linux-Fake-Background-Webcam#44]
I have an old webcam, so it works best at 640x480. However, it errors out if I specify something that isn't 1280x720 (default) for size, despite the fact I can't find 720 anywhere in the code (I tried changing the default).

```
Traceback (most recent call last):
  File "./fake.py", line 364, in <module>
    main()
  File "./fake.py", line 360, in main
    loop.run_until_complete(cam.run())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "./fake.py", line 274, in run
    self.put_frame(frame)
  File "./fake.py", line 254, in put_frame
    self.fake_cam.schedule_frame(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
  File "/home/ryan/src/third-party/Linux-Fake-Background-Webcam/venv/lib/python3.7/site-packages/pyfakewebcam/pyfakewebcam.py", line 68, in schedule_frame
    raise Exception('frame height does not match the height of webcam device: {}!={}\n'.format(self._settings.fmt.pix.height, frame.shape[0]))
Exception: frame height does not match the height of webcam device: 720!=480
```

I'm using v4l2loopback 0.12.5 backported to Debian Buster (running a backports kernel). I have the latest python modules installed in a venv.

**Comment by fangfufu** [comment]
Could you tell me what command you use to run fake.py, please? and did you do any modification to the code? The code does set the default webcam resolution.

**Comment by coleman-da-traveling-nerd** [comment]
Also adding as I was struggling with this error.  Same as above, make sure zoom is set to "Original Ratio," but also try to have the camera be uninitialized by Cheese, Zoom, etc. when starting up your terminal call for fake.py

Then you can change the webcam in Zoom or whatever app to the "fake-cam."  While Zoom, Cheese, etc. is open and actively using the webcam, I got this error and couldn't for the life of me figure out why.  Simply turning everything off and doing this from an unused state got me results.
