### ISSUE TITLE
problems with tensorflow and node on fedora 32

### ISSUE THREAD

**Issue by damnms** [fangfufu/Linux-Fake-Background-Webcam#60]
i tried the same as oli and root
```
[root@DESKTOP-DM65VNV bodypix]# node app.js 
Found a GPU at /dev/nvidia0
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '@tensorflow/tfjs-node-gpu'
Require stack:
- /home/oli/Downloads/Linux-Fake-Background-Webcam/bodypix/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at tensorflow (/home/oli/Downloads/Linux-Fake-Background-Webcam/bodypix/app.js:42:16)
    at Object.<anonymous> (/home/oli/Downloads/Linux-Fake-Background-Webcam/bodypix/app.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/oli/Downloads/Linux-Fake-Background-Webcam/bodypix/app.js' ]
}
```

**Comment by fangfufu** [comment]
It appears that you have'nt installed tensorflow-js properly.
