### ISSUE TITLE
problems with running - opencv

### ISSUE THREAD

**Issue by Adam-Gibbs** [fangfufu/Linux-Fake-Background-Webcam#65]
I have tried to run `python3 fake.py` and I always get this error:

```
Cannot set camera property 3 to 1280, used value: 0.0
Cannot set camera property 4 to 720, used value: 0.0
Cannot set camera property 5 to 30, used value: 0.0
Running...
Please CTRL-C to reload the background / foreground images
Please CTRL-\ to exit
Traceback (most recent call last):
  File "fake.py", line 397, in <module>
    main()
  File "fake.py", line 393, in main
    loop.run_until_complete(cam.run())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "fake.py", line 282, in run
    await self.load_images()
  File "fake.py", line 176, in load_images
    background = cv2.resize(background, (self.width, self.height))
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-vu_aq9yd/opencv/modules/imgproc/src/resize.cpp:3932: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
```

**Comment by fangfufu** [comment]
You might not have specified your real webcam properly. The real webcam definitely failed to open.
