### ISSUE TITLE
[Docker GPU] Error in fakecam when running container

### ISSUE THREAD

**Issue by mhSangar** [fangfufu/Linux-Fake-Background-Webcam#66]
When running the container for `fakecam`, I get the following error:

```shell
Cannot set camera property 3 to 1280, used value: 640.0
Cannot set camera property 4 to 720, used value: 480.0
Traceback (most recent call last):
  File "fake.py", line 397, in <module>
    main()
  File "fake.py", line 368, in main
    cam = FakeCam(
  File "fake.py", line 118, in __init__
    self.fake_cam = pyfakewebcam.FakeWebcam(v4l2loopback_path, self.width, self.height)
  File "/usr/local/lib/python3.8/dist-packages/pyfakewebcam/pyfakewebcam.py", line 54, in __init__
    fcntl.ioctl(self._video_device, _v4l2.VIDIOC_S_FMT, self._settings)
OSError: [Errno 22] Invalid argument
```

Any guidance from here? I leave below the command I used to run the container:

```shell
docker run -d \
   --name=fakecam \
  --network=fakecam \
  --device=/dev/video0:/dev/video0 \
  --device=/dev/video1:/dev/video2 \
  -v fakecam:/socket \
  fakecam \
  -B /socket/bodypix.sock --no-foreground --scale-factor 1
```

Thanks in advance, the repository looks pretty cool! ^^

**Comment by timarandras** [comment]
same here. Set volume in docker-compose.yml to an existing jpg. Set devices to input video0 and output video1.

**Comment by mworthley** [comment]
Check the latest version. It has some convenience updates using compose and an env file.

**Comment by fangfufu** [comment]
This is no longer relevant, as I am using Mediapipe as the backend. Please check out the latest commit.
