### ISSUE TITLE
Background Image is read in as video

### ISSUE THREAD

**Issue by seschu** [fangfufu/Linux-Fake-Background-Webcam#72]
i am trying to load another background image but I keep getting this error

Traceback (most recent call last):
  File "./fake.py", line 397, in <module>
    main()
  File "./fake.py", line 393, in main
    loop.run_until_complete(cam.run())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "./fake.py", line 297, in run
    frame = await self.mask_frame(session, frame)
  File "./fake.py", line 260, in mask_frame
    background_frame = next(self.images["background"])
  File "./fake.py", line 202, in next_frame
    self.bg_video_adv_rate = round(self.bg_video_fps/self.current_fps)
ZeroDivisionError: float division by zero

**Comment by fangfufu** [comment]
Sorry for the late reply. Have you checked if the output device is working? ``self.current_fps`` is set by the output webcam.

**Comment by fangfufu** [comment]
Closing old ticket. Please check out the latest commit. If the problem still exists, please feel free to reopen the ticket.

**Comment by amamut** [comment]
I'm getting the same issue with a .jpg which I can open with `feh`: 
```
Running...
Please CTRL-C to pause and reload the background / foreground images
Please CTRL-\ to exit
[ERROR:0] global /tmp/pip-req-build-agffqapq/opencv/modules/videoio/src/cap.cpp (160) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.3) /tmp/pip-req-build-agffqapq/opencv/modules/videoio/src/cap_images.cpp:293: error: (-215:Assertion failed) !_filename.empty() in function 'open'


Traceback (most recent call last):
  File "/home/amamut/projects/lib/Linux-Fake-Background-Webcam/./fake.py", line 517, in <module>
    main()
  File "/home/amamut/projects/lib/Linux-Fake-Background-Webcam/./fake.py", line 513, in main
    cam.run()
  File "/home/amamut/projects/lib/Linux-Fake-Background-Webcam/./fake.py", line 290, in run
    self.load_images()
  File "/home/amamut/projects/lib/Linux-Fake-Background-Webcam/./fake.py", line 177, in load_images
    raise RuntimeError("Couldn't open video '{}'".format(
RuntimeError: Couldn't open video '/home/amamut/projects/personal/dotfiles/wallpapers/MrsHappy-445-2-1024x736.jpg'
```
