### ISSUE TITLE
Animated image load failure

### ISSUE THREAD

**Issue by Guyverix** [fangfufu/Linux-Fake-Background-Webcam#77]
Dont think this is a failure with this app specifically, but having followed the README, I have the system working with static jpg images.  I can change them out, and am successfully able to use all other command switches.  However whenever I use the -b and point to gif, or webm, or webp the application kicks up an OpenCV error.  

Any suggestions on how I can debug this further?
chubbard@guyver-office:~/160_ssd/Linux-Fake-Background-Webcam/fakecam$ python3 fake.py -v /dev/video20 -B http://127.0.0.1:9001  --no-foreground -b /home/chubbard/Pictures/anime_girl.webp
Cannot set camera property 3 to 1280, used value: 640.0
Cannot set camera property 5 to 30, used value: 7.5
Running...
Please CTRL-C to reload the background / foreground images
Please CTRL-\ to exit
[ERROR:0] global /io/opencv/modules/videoio/src/cap.cpp (116) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.2.0) /io/opencv/modules/videoio/src/cap_images.cpp:293: error: (-215:Assertion failed) !_filename.empty() in function 'open'

Traceback (most recent call last):
  File "fake.py", line 397, in <module>
    main()
  File "fake.py", line 393, in main
    loop.run_until_complete(cam.run())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "fake.py", line 297, in run
    frame = await self.mask_frame(session, frame)
  File "fake.py", line 260, in mask_frame
    background_frame = next(self.images["background"])
  File "fake.py", line 202, in next_frame
    self.bg_video_adv_rate = round(self.bg_video_fps/self.current_fps)
ZeroDivisionError: float division by zero

**Comment by RobinSchapendonk** [comment]
I just deleted the `background`, `foreground` and `foreground-mask` (default) images, and then placed my mp4 file named `background.mp4` in the `fakecam` directory

**Comment by Guyverix** [comment]
Thank you very much!  I will attempt this next!  So guessing full videos will work, but animated GIFs or things like that give it heartburn.  Very strange, but interesting to play with.
