### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by baschi29** [fangfufu/Linux-Fake-Background-Webcam#80]
Hello, I kinda need some help to try to fix my problem. I'm always getting the following error while trying to run fake.py

```
python3 fake.py -w /dev/video2
Cannot set camera property 3 to 1280, used value: 640.0
Cannot set camera property 5 to 30, used value: 10.0
Traceback (most recent call last):
  File "fake.py", line 397, in <module>
    main()
  File "fake.py", line 368, in main
    cam = FakeCam(
  File "fake.py", line 118, in __init__
    self.fake_cam = pyfakewebcam.FakeWebcam(v4l2loopback_path, self.width, self.height)
  File "/home/basti/.local/lib/python3.8/site-packages/pyfakewebcam/pyfakewebcam.py", line 54, in __init__
    fcntl.ioctl(self._video_device, _v4l2.VIDIOC_S_FMT, self._settings)
OSError: [Errno 22] Invalid argument
```
I don't think this is a duplicate of #68 as I tried every possible video device and it seems to load some values at the beginning.
I installed like mentioned on the github page. I'm using v4l2loopback, but already tried akvcam with no success.

**Comment by baschi29** [comment]
Ok, I got it, I needed to specify the v4l2loopback path. My bad
