### ISSUE TITLE
node:internal/modules/cjs/loader:926 when $ node app.js

### ISSUE THREAD

**Issue by filipejunqueira** [fangfufu/Linux-Fake-Background-Webcam#86]
Sorry for the perhaps obvious question, but I'm getting this when running node app.js
Anyone know what could that be?

Found a GPU at /dev/nvidia0
node:internal/modules/cjs/loader:926
  throw err;
  ^

Error: Cannot find module '@tensorflow/tfjs-node-gpu'
Require stack:
- /home/myuser/software/fake_background_cam/bodypix/app.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
    at Function.Module._load (node:internal/modules/cjs/loader:768:27)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at tensorflow (/home/myuser/software/fake_background_cam/bodypix/app.js:48:16)
    at Object.<anonymous> (/home/myuser/software/fake_background_cam/bodypix/app.js:9:12)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/myuser/software/fake_background_cam/bodypix/app.js'
  ]
}

**Comment by filipejunqueira** [comment]
Issue resolved. I forgot to install... :-P
