### ISSUE TITLE
FileNotFoundError: device does not exist: /dev/video2

### ISSUE THREAD

**Issue by dysonsphere-startmail** [fangfufu/Linux-Fake-Background-Webcam#96]
I had this working well yesterday.
Installed as per the README.

Since rebooting today it will not run.

I get the following output when running:

.../bodypix$ node app.js
```
Found a GPU at /dev/nvidia0
2021-04-27 11:36:40.627157: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-04-27 11:36:40.657638: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3094355000 Hz
2021-04-27 11:36:40.658630: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x53f2730 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-04-27 11:36:40.658662: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-04-27 11:36:40.659372: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-04-27 11:36:40.692880: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-27 11:36:40.693230: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.455
pciBusID: 0000:07:00.0
2021-04-27 11:36:40.693288: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory
2021-04-27 11:36:40.693324: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory
2021-04-27 11:36:40.693346: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory
2021-04-27 11:36:40.693368: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory
2021-04-27 11:36:40.693388: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory
2021-04-27 11:36:40.693410: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory
2021-04-27 11:36:40.693431: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory
2021-04-27 11:36:40.693436: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-04-27 11:36:40.744833: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-04-27 11:36:40.744857: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2021-04-27 11:36:40.744862: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
```
.../fakecam$ python3 fake.py
```
Real camera original values are set as: 640x480 with 30 FPS and video codec 1448695129
Real camera new values are set as: 1280x720 with 30 FPS and video codec 1196444237

--- Make sure the v4l2loopback kernel module is loaded ---
sudo modprobe v4l2loopback devices=1

Traceback (most recent call last):
  File "fake.py", line 468, in <module>
    main()
  File "fake.py", line 437, in main
    cam = FakeCam(
  File "fake.py", line 160, in __init__
    self.fake_cam = pyfakewebcam.FakeWebcam(v4l2loopback_path, self.width, self.height)
  File "/home/kdys/.local/lib/python3.8/site-packages/pyfakewebcam/pyfakewebcam.py", line 31, in __init__
    raise FileNotFoundError('device does not exist: {}'.format(video_device))
FileNotFoundError: device does not exist: /dev/video2
```
Any ideas as to why this is happening after a reboot, and how to fix it would be much appreciated.
Thanks

**Comment by fangfufu** [comment]
You haven't installed CUDA libraries correctly.

**Comment by dysonsphere-startmail** [comment]
Any ideas on how to get those libraries installed properly on Ubuntu 20.04 (Pop_OS!)?
I have purged nvida and cuda and reinstalled them, along with TensorRT, from these instructions:
[(https://www.tensorflow.org/install/gpu)](https://www.tensorflow.org/install/gpu)
Same libraries show up as missing.
I then purged again and installed CUDA from [this](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&=Ubuntu&target_version=20.04&target_type=deb_local)
and
TensorRT from [this](https://developer.nvidia.com/nvidia-tensorrt-7x-download)
Again the same libraries missing messages when running node app.js
```
Found a GPU at /dev/nvidia0
2021-04-27 16:11:12.384318: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-04-27 16:11:12.421449: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3094215000 Hz
2021-04-27 16:11:12.422424: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x594a720 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-04-27 16:11:12.422445: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-04-27 16:11:12.426046: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-04-27 16:11:12.466925: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-27 16:11:12.467438: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: NVIDIA GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.455
pciBusID: 0000:07:00.0
2021-04-27 16:11:12.467496: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory
2021-04-27 16:11:12.467523: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory
2021-04-27 16:11:12.467550: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory
2021-04-27 16:11:12.467577: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory
2021-04-27 16:11:12.467602: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory
2021-04-27 16:11:12.467630: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory
2021-04-27 16:11:12.467655: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory
2021-04-27 16:11:12.467660: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-04-27 16:11:12.517109: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-04-27 16:11:12.517132: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2021-04-27 16:11:12.517138: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
```

**Comment by fangfufu** [comment]
You can run this tool without the Nvidia stuff, have you tried that? There are a lot of tutorials on how to do this kind of thing on the Internet. I don't have Nvidia graphics on my laptop, so I wouldn't know myself. A lot of patches are contributed by people on the Internet.

**Comment by dysonsphere-startmail** [comment]
OK. Not sure how to force it to run on the CPU, but I will look into trying that.  Thanks.
