### ISSUE TITLE
Akvcam install

### ISSUE THREAD

**Issue by Thatoo** [fangfufu/Linux-Fake-Background-Webcam#98]
After uninstalling v4l2loopback-dkms as explain in https://github.com/fangfufu/Linux-Fake-Background-Webcam/issues/97, I have tried to install Akvcam by downloading it and do a
`sudo dkms install akvcam/1.2.0`
Then, I copied fakecam/akvcam to /etc/.

I ran again ./install.sh to be sure it gets that I want to use Akvcam now but it didn't mention anything, just said 
```
up to date, audited 129 packages in 1s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilitie
```
Then I launched on one terminal
```
cd bodypix
node app.js
```

and on the second one
```
cd fakecam
python3 fake.py
```

I got this error : 
```
Real camera original values are set as: 640x480 with 30 FPS and video codec 1448695129
Cannot set camera property 3 to 1280. Defaulting to auto-detected property set by opencv
Cannot set camera property 4 to 720. Defaulting to auto-detected property set by opencv
Real camera new values are set as: 640x480 with 30 FPS and video codec 1196444237

--- Make sure the v4l2loopback kernel module is loaded ---
sudo modprobe v4l2loopback devices=1

Traceback (most recent call last):
  File "fake.py", line 468, in <module>
    main()
  File "fake.py", line 437, in main
    cam = FakeCam(
  File "fake.py", line 160, in __init__
    self.fake_cam = pyfakewebcam.FakeWebcam(v4l2loopback_path, self.width, self.height)
  File "/home/nleprette/.local/lib/python3.8/site-packages/pyfakewebcam/pyfakewebcam.py", line 31, in __init__
    raise FileNotFoundError('device does not exist: {}'.format(video_device))
FileNotFoundError: device does not exist: /dev/video2

```
I feel like it still want to use v4l2loopback instead of Akvcam plus I can read that it has set my webcam to 

> Real camera new values are set as: 640x480 with 30 FPS and video codec

Which might explain why since I'm trying to make fakewebcam working I feel that quality of my webcam has decreased severely... Could be?

**Comment by fangfufu** [comment]
Where does it actually say ``--- Make sure the v4l2loopback kernel module is loaded ---``? It is nowhere to be found in my code. I have no idea what you did.

**Comment by Thatoo** [comment]
> Where does it actually say `--- Make sure the v4l2loopback kernel module is loaded ---`? It is nowhere to be found in my code. I have no idea what you did.

when I do (after uninstalling v4l2loopback-dkms and installing Akvcam)
```
cd fakecam
python3 fake.py
```

**Comment by Thatoo** [comment]
Indeed it is written in the list of possible option If one is not running fake.py under Docker. I think it could be highlighted. I'll make a PR for that.

Unfortunately, I get an error at launch : 

```
$ python3 fake.py --akvcam
Real camera original values are set as: 640x480 with 30 FPS and video codec 1448695129
Cannot set camera property 3 to 1280. Defaulting to auto-detected property set by opencv
Cannot set camera property 4 to 720. Defaulting to auto-detected property set by opencv
Real camera new values are set as: 640x480 with 30 FPS and video codec 1196444237
Traceback (most recent call last):
  File "fake.py", line 468, in <module>
    main()
  File "fake.py", line 437, in main
    cam = FakeCam(
  File "fake.py", line 162, in __init__
    self.fake_cam = AkvCameraWriter(v4l2loopback_path, self.width, self.height)
  File "/home/USER/Applications/Linux-Fake-Background-Webcam-master/fakecam/akvcam.py", line 14, in __init__
    self.d = self.open_camera()
  File "/home/USER/Applications/Linux-Fake-Background-Webcam-master/fakecam/akvcam.py", line 20, in open_camera
    d = os.open(self.webcam, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/video2'
Exception ignored in: <function AkvCameraWriter.__del__ at 0x7fb4c5622c10>
Traceback (most recent call last):
  File "/home/USER/Applications/Linux-Fake-Background-Webcam-master/fakecam/akvcam.py", line 48, in __del__
    self.queue.put(None)
AttributeError: 'AkvCameraWriter' object has no attribute 'queue'
```

**Comment by fangfufu** [comment]
Have you installed akvcam properly?

**Comment by fangfufu** [comment]
No, your node.js stuff is fine, it should fall back to CPU.

**Comment by Thatoo** [comment]
I tried to launch it with sudo and I got an other error : 

```
$ sudo python3 fake.py --akvcam
Traceback (most recent call last):
  File "fake.py", line 12, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
$
```
Does that help?

**Comment by fangfufu** [comment]
You need to install aiohttp module by pip3 install aiohttp

**Comment by Thatoo** [comment]
OK, I did it, error has changed... work in progress I'd say :-)
```
$ sudo pip3 install aiohttp
...
Successfully installed aiohttp-3.7.4.post0 async-timeout-3.0.1 multidict-5.1.0 typing-extensions-3.10.0.0 yarl-1.6.3
$ sudo python3 fake.py --akvcam
Traceback (most recent call last):
  File "fake.py", line 13, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
$ sudo pip3 install cv2
ERROR: Could not find a version that satisfies the requirement cv2 (from versions: none)
ERROR: No matching distribution found for cv2
```

too bad, I thought it was going to work...

**Comment by Thatoo** [comment]
It looks like the same error as https://github.com/fangfufu/Linux-Fake-Background-Webcam/issues/68
doesn't it?

**Comment by Thatoo** [comment]
ahaha, I found something. Still WIP...
I simply did
`$sudo modprobe akvcam`
then

```
$ node app.js
No GPU found at /dev/nvidia0, using CPU
2021-05-11 21:03:29.384082: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-05-11 21:03:29.415004: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3399905000 Hz
2021-05-11 21:03:29.415368: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x6b5be30 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-05-11 21:03:29.415456: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Platform node has already been set. Overwriting the platform with [object Object].
/home/USER/Applications/Linux-Fake-Background-Webcam-master/bodypix/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:542
                out = _this.tidy(function () { return forwardFunc(_this.backend, saveFunc_1); });
                                                      ^

TypeError: forwardFunc is not a function
    at /home/USER/Applications/Linux-Fake-Background-Webcam-master/bodypix/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:542:55
    at /home/USER/Applications/Linux-Fake-Background-Webcam-master/bodypix/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:388:22
    at Engine.scopedRun (/home/USER/Applications/Linux-Fake-Background-Webcam-master/bodypix/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:398:23)
    at Engine.tidy (/home/USER/Applications/Linux-Fake-Background-Webcam-master/bodypix/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:387:21)
    at kernelFunc (/home/USER/Applications/Linux-Fake-Background-Webcam-master/bodypix/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:542:29)
    at /home/USER/Applications/Linux-Fake-Background-Webcam-master/bodypix/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:553:27
    at Engine.scopedRun (/home/USER/Applications/Linux-Fake-Background-Webcam-master/bodypix/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:398:23)
    at Engine.runKernelFunc (/home/USER/Applications/Linux-Fake-Background-Webcam-master/bodypix/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:551:14)
    at Engine.runKernel (/home/USER/Applications/Linux-Fake-Background-Webcam-master/bodypix/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-core/dist/engine.js:449:21)
    at pad_ (/home/USER/Applications/Linux-Fake-Background-Webcam-master/bodypix/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:15476:19)
$
```

and
```
$cd fakecam
$python3 fake.py
```
and it seems to flow as the image below

![image](https://user-images.githubusercontent.com/464782/117871251-75bf1a00-b29d-11eb-970a-72cddf16eac3.png)

**Comment by Thatoo** [comment]
Yes, it allows me to choose akvcam in jitsi

![image](https://user-images.githubusercontent.com/464782/117871723-0b5aa980-b29e-11eb-908a-0e23ee18be3e.png)

**Comment by fangfufu** [comment]
Your node.js isn't working. I think you should try and run the docker version.

**Comment by Thatoo** [comment]
```
$ sudo apt remove --purge nodejs
$ curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -
$ sudo apt-get install -y nodejs
$ sudo reboot
$ sudo modprobe akvcam
```

I removed the Linux-Fake-Background-Webcam-master folder, downloaded it again

```
$ ./install.sh
$ cd bodypix
$ node app.js
```
and on other terminal

```
cd fakecam
python3 fake.py --akvcam
```

It works!
Awesome!

So as a record, what I was missing was
- **Nodejs 12 is mandatory** (not the latest version of nodejs) . Maybe with Nodejs12, it would also work with v4l2loopback-dkms but I won't test it now that it's working with akvcam :-)
- **`sudo modprobe akvcam` after reboot**

**Comment by fangfufu** [comment]
Congratulations!

**Comment by Thatoo** [comment]
I really hope that will become a plugin for Webcamoid to make it easy for everyone. Moreover that Webcamoid exist as an appimage...!
Could be nice on OBS too for some people.

One improvement I'd hope will come is a blur option we could launch like
`$ python3 fake.py --akvcam --blur`
and the background becomes blur but not our face. It's not as fun as changing the background but for working environment is great. We could even imagine a degree of blur (between 1 almost no blur effect and 10, very much blur effect) like
 `$ python3 fake.py --akvcam --blur 5`

Anyway, congrats for the work you've done so far and thank you for your help!

**Comment by ShayBox** [comment]
Webcamoid has very high latency, it's just not designed to be fast, so a plugin for it wouldn't be a good idea

`AttributeError: 'AkvCameraWriter' object has no attribute 'queue'` fakecam --akvcam

**Comment by fangfufu** [comment]
Please checkout the latest commit. I got rid off Bodypix. Node.js is no longer required.

**Comment by Thatoo** [comment]
How to uninstall properly the previous version with it's prerequisite at this time in order to install properly the new version?

**Comment by fangfufu** [comment]
@Thatoo , you don't really need to uninstall the older version. You can just install the new Python requirements. It should replace the older dependencies with the newer ones for you. You can delete the older repository if Git doesn't update it for you properly.
